// Definición de permisos
const PERMISOS = {
  // Permisos de administración
  ADMIN_TOTAL: 'ADMIN_TOTAL', // Acceso completo al sistema
  
  // Permisos de gestión de usuarios
  VER_USUARIOS: 'VER_USUARIOS',
  CREAR_USUARIOS: 'CREAR_USUARIOS',
  EDITAR_USUARIOS: 'EDITAR_USUARIOS',
  ELIMINAR_USUARIOS: 'ELIMINAR_USUARIOS',
  
  // Permisos de sala de espera
  VER_SALA_ESPERA: 'VER_SALA_ESPERA',
  AGREGAR_PACIENTE_ESPERA: 'AGREGAR_PACIENTE_ESPERA',
  MOVER_A_CONSULTA: 'MOVER_A_CONSULTA',
  MOVER_A_HOSPITALIZACION: 'MOVER_A_HOSPITALIZACION',
  
  // Permisos de consulta
  VER_CONSULTAS: 'VER_CONSULTAS',
  CREAR_CONSULTA: 'CREAR_CONSULTA',
  EDITAR_CONSULTA: 'EDITAR_CONSULTA',
  FINALIZAR_CONSULTA: 'FINALIZAR_CONSULTA',
  
  // Permisos de hospitalización
  VER_HOSPITALIZACION: 'VER_HOSPITALIZACION',
  CREAR_HOSPITALIZACION: 'CREAR_HOSPITALIZACION',
  EDITAR_HOSPITALIZACION: 'EDITAR_HOSPITALIZACION',
  DAR_ALTA_HOSPITALIZACION: 'DAR_ALTA_HOSPITALIZACION',
  
  // Permisos de historiales médicos
  VER_HISTORIALES: 'VER_HISTORIALES',
  CREAR_HISTORIAL: 'CREAR_HISTORIAL',
  EDITAR_HISTORIAL: 'EDITAR_HISTORIAL',
  ELIMINAR_HISTORIAL: 'ELIMINAR_HISTORIAL',
  
  // Permisos de facturación
  VER_FACTURAS: 'VER_FACTURAS',
  CREAR_FACTURA: 'CREAR_FACTURA',
  EDITAR_FACTURA: 'EDITAR_FACTURA',
  ANULAR_FACTURA: 'ANULAR_FACTURA',
  
  // Permisos de reportes
  VER_REPORTES: 'VER_REPORTES',
  EXPORTAR_REPORTES: 'EXPORTAR_REPORTES'
};

// Definición de roles y sus permisos asociados
const ROLES = {
  ADMINISTRADOR: {
    nombre: 'Administrador',
    permisos: Object.values(PERMISOS)
  },
  
  VETERINARIO: {
    nombre: 'Veterinario',
    permisos: [
      PERMISOS.VER_SALA_ESPERA,
      PERMISOS.AGREGAR_PACIENTE_ESPERA,
      PERMISOS.MOVER_A_CONSULTA,
      PERMISOS.MOVER_A_HOSPITALIZACION,
      PERMISOS.VER_CONSULTAS,
      PERMISOS.CREAR_CONSULTA,
      PERMISOS.EDITAR_CONSULTA,
      PERMISOS.FINALIZAR_CONSULTA,
      PERMISOS.VER_HOSPITALIZACION,
      PERMISOS.CREAR_HOSPITALIZACION,
      PERMISOS.EDITAR_HOSPITALIZACION,
      PERMISOS.DAR_ALTA_HOSPITALIZACION,
      PERMISOS.VER_HISTORIALES,
      PERMISOS.CREAR_HISTORIAL,
      PERMISOS.EDITAR_HISTORIAL,
      PERMISOS.VER_FACTURAS,
      PERMISOS.CREAR_FACTURA,
      PERMISOS.VER_REPORTES
    ]
  },
  
  RECEPCIONISTA: {
    nombre: 'Recepcionista',
    permisos: [
      PERMISOS.VER_SALA_ESPERA,
      PERMISOS.AGREGAR_PACIENTE_ESPERA,
      PERMISOS.VER_CONSULTAS,
      PERMISOS.VER_HOSPITALIZACION,
      PERMISOS.VER_HISTORIALES,
      PERMISOS.VER_FACTURAS,
      PERMISOS.CREAR_FACTURA,
      PERMISOS.EDITAR_FACTURA
    ]
  },
  
  AUXILIAR_VETERINARIO: {
    nombre: 'Auxiliar Veterinario',
    permisos: [
      PERMISOS.VER_SALA_ESPERA,
      PERMISOS.VER_CONSULTAS,
      PERMISOS.VER_HOSPITALIZACION,
      PERMISOS.EDITAR_HOSPITALIZACION,
      PERMISOS.VER_HISTORIALES,
      PERMISOS.CREAR_HISTORIAL
    ]
  },
  
  CONTABLE: {
    nombre: 'Contable',
    permisos: [
      PERMISOS.VER_FACTURAS,
      PERMISOS.CREAR_FACTURA,
      PERMISOS.EDITAR_FACTURA,
      PERMISOS.ANULAR_FACTURA,
      PERMISOS.VER_REPORTES,
      PERMISOS.EXPORTAR_REPORTES
    ]
  }
};

module.exports = {
  PERMISOS,
  ROLES
}; 